default: &default
  google:
    client_id: <%= ENV.fetch('GOOGLE_CLIENT_ID', nil) %>
    client_secret: <%= ENV.fetch('GOOGLE_CLIENT_SECRET', nil) %>

  sendinblue:
    api_key: <%= ENV.fetch('SENDINBLUE_API_KEY', nil) %>

  eid:
    url: <%= ENV.fetch('AUTH_EID_URL', nil) %>
    public_key: <%= ENV.fetch('AUTH_EID_PUBLIC_KEY', nil).inspect %>

development:
  <<: *default

test:
  <<: *default
  sendinblue:
    api_key: ''

staging:
  <<: *default

production:
  <<: *default
