name: Review app on staging

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2        
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
          
      - name: Register deployment
        uses: bobheadxi/deployments@v0.5.2
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: staging
          
      - uses: dokku/github-action@master
        with:
          git_push_flags: '--force'
          git_remote_url: ssh://dokku@${{secrets.STAGING_HOST}}/${{github.event.repository.name}}
          ssh_private_key: ${{secrets.STAGING_KEY}}
      
      - name: Update deployment status
        uses: bobheadxi/deployments@v0.5.2
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://staging.navody.digital
